// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;

      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVsOfCGyLjpQIVDJlzr45qEIgAXN3CDFI',
    appId: '1:988282119245:android:835d90ff61100bcf442804',
    messagingSenderId: '988282119245',
    projectId: 'local-basic-test-4fa53',
    databaseURL: 'https://local-basic-test-4fa53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'local-basic-test-4fa53.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAcaIk9NL4VYAAzFqi1o6z5BkgLGFhLTM',
    appId: '1:988282119245:ios:220ee10b94b30682442804',
    messagingSenderId: '988282119245',
    projectId: 'local-basic-test-4fa53',
    databaseURL: 'https://local-basic-test-4fa53-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'local-basic-test-4fa53.firebasestorage.app',
    iosBundleId: 'com.example.firebaseFlutterBasic',
  );

}